<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>Chess.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Images\ChessPieces\Source\Bishop.png" />
    <Resource Include="Images\ChessPieces\Source\King.png" />
    <Resource Include="Images\ChessPieces\Source\Knight-white.png" />
    <Resource Include="Images\ChessPieces\Source\Pawn-white.png" />
    <Resource Include="Images\ChessPieces\Source\Queen-white.png" />
    <Resource Include="Images\ChessPieces\Source\Rook.png" />
    <Resource Include="Images\ChessPieces\Source\Source.txt" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\Chess.png" />
    <Resource Include="Images\Source.txt" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Chess.ico" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\ChessPieces\PNG\Bishop-black.png" />
    <Resource Include="Images\ChessPieces\PNG\Bishop-white.png" />
    <Resource Include="Images\ChessPieces\PNG\King-black.png" />
    <Resource Include="Images\ChessPieces\PNG\King-white.png" />
    <Resource Include="Images\ChessPieces\PNG\Knight-black.png" />
    <Resource Include="Images\ChessPieces\PNG\Knight-white.png" />
    <Resource Include="Images\ChessPieces\PNG\Pawn-black.png" />
    <Resource Include="Images\ChessPieces\PNG\Pawn-white.png" />
    <Resource Include="Images\ChessPieces\PNG\Queen-black.png" />
    <Resource Include="Images\ChessPieces\PNG\Queen-white.png" />
    <Resource Include="Images\ChessPieces\PNG\Rook-black.png" />
    <Resource Include="Images\ChessPieces\PNG\Rook-white.png" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Chess.Model\obj\Debug\net7.0\.NETCoreApp,Version=v7.0.AssemblyAttributes.cs" />
    <Compile Remove="Chess.Model\obj\Debug\net7.0\Chess.Model.AssemblyInfo.cs" />
    <Compile Remove="Chess.Model\obj\Debug\net7.0\Chess.Model.GlobalUsings.g.cs" />
    <Compile Remove="Chess.Model\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs" />
    <Compile Remove="Chess.Model\obj\Debug\net8.0\Chess.Model.AssemblyInfo.cs" />
    <Compile Remove="Chess.Model\obj\Debug\net8.0\Chess.Model.GlobalUsings.g.cs" />
    <Compile Remove="Chess.ViewModel\obj\Debug\net7.0\.NETCoreApp,Version=v7.0.AssemblyAttributes.cs" />
    <Compile Remove="Chess.ViewModel\obj\Debug\net7.0\Chess.ViewModel.AssemblyInfo.cs" />
    <Compile Remove="Chess.ViewModel\obj\Debug\net7.0\Chess.ViewModel.GlobalUsings.g.cs" />
    <Compile Remove="Chess.ViewModel\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs" />
    <Compile Remove="Chess.ViewModel\obj\Debug\net8.0\Chess.ViewModel.AssemblyInfo.cs" />
    <Compile Remove="Chess.ViewModel\obj\Debug\net8.0\Chess.ViewModel.GlobalUsings.g.cs" />
    <Compile Remove="Chess.WinUI\obj\x64\Debug\net7.0-windows10.0.22621.0\.NETCoreApp,Version=v7.0.AssemblyAttributes.cs" />
    <Compile Remove="Chess.WinUI\obj\x64\Debug\net7.0-windows10.0.22621.0\Chess.WinUI.AssemblyInfo.cs" />
    <Compile Remove="Chess.WPF\obj\Debug\net7.0-windows\.NETCoreApp,Version=v7.0.AssemblyAttributes.cs" />
    <Compile Remove="Chess.WPF\obj\Debug\net7.0-windows\App.g.cs" />
    <Compile Remove="Chess.WPF\obj\Debug\net7.0-windows\App.g.i.cs" />
    <Compile Remove="Chess.WPF\obj\Debug\net7.0-windows\Chess.WPF.AssemblyInfo.cs" />
    <Compile Remove="Chess.WPF\obj\Debug\net7.0-windows\Chess.WPF_2opvrzs4_wpftmp.AssemblyInfo.cs" />
    <Compile Remove="Chess.WPF\obj\Debug\net7.0-windows\GeneratedInternalTypeHelper.g.cs" />
    <Compile Remove="Chess.WPF\obj\Debug\net7.0-windows\GeneratedInternalTypeHelper.g.i.cs" />
    <Compile Remove="Chess.WPF\obj\Debug\net7.0-windows\MainWindow.g.cs" />
    <Compile Remove="Chess.WPF\obj\Debug\net7.0-windows\MainWindow.g.i.cs" />
    <Compile Remove="Chess.WPF\obj\Debug\net8.0-windows\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs" />
    <Compile Remove="Chess.WPF\obj\Debug\net8.0-windows\App.g.cs" />
    <Compile Remove="Chess.WPF\obj\Debug\net8.0-windows\App.g.i.cs" />
    <Compile Remove="Chess.WPF\obj\Debug\net8.0-windows\Chess.WPF.AssemblyInfo.cs" />
    <Compile Remove="Chess.WPF\obj\Debug\net8.0-windows\Chess.WPF_0zb1kdd4_wpftmp.AssemblyInfo.cs" />
    <Compile Remove="Chess.WPF\obj\Debug\net8.0-windows\Chess.WPF_jax5g4ps_wpftmp.AssemblyInfo.cs" />
    <Compile Remove="Chess.WPF\obj\Debug\net8.0-windows\GeneratedInternalTypeHelper.g.cs" />
    <Compile Remove="Chess.WPF\obj\Debug\net8.0-windows\GeneratedInternalTypeHelper.g.i.cs" />
    <Compile Remove="Chess.WPF\obj\Debug\net8.0-windows\MainWindow.g.cs" />
    <Compile Remove="Chess.WPF\obj\Debug\net8.0-windows\MainWindow.g.i.cs" />
  </ItemGroup>
</Project>